### ISSUE TITLE
envoy charm does observe `grpc-relation-broken` event

### ISSUE THREAD

**Issue by orfeas-k** [canonical/envoy-operator#105]
### Bug Description

This means that if the relation is broken, the charm will remain active. This should be a small fix in line https://github.com/canonical/envoy-operator/blob/2d4526b555c1caffcef36011c46209e8183b806b/src/components/k8s_service_info_requirer_component.py#L42.

```diff
        self._events_to_observe = [self._k8s_service_info_requirer.on.updated, self.charm.on[relation_name].relation_broken,]
```

### To Reproduce

N/A

### Environment

N/A

### Relevant Log Output

```shell
N/A
```

**Comment by mvlassis** [comment]
- I tried reproducing the issue but I wasn't able to; The `envoy` charm's status turns to `blocked` as soon as the `grpc` relation is blocked.
- The `KubernetesServiceInfoRequirer` object that is created by the `K8sServiceInfoRequirerComponent` class [during initialization](https://github.com/canonical/envoy-operator/blob/4e1f3bd1b508925da7cd419e27b318f5774358b8/src/components/k8s_service_info_requirer_component.py#L37), seems to observe both `relation-changed` and `relation-broken` events. This can be seen in the library's code [here](https://github.com/canonical/mlops-libs/blob/985228fa8439898a3da594f4973771bbfbe639db/lib/charms/mlops_libs/v0/k8s_service_info.py#L197). That would explain why the charm's status correctly changes to `blocked`.
- @orfeas-k mentioned that he is unsure of whether this issue has been reproduced in version 1.9, so we have decided to close the issue.
