### ISSUE TITLE
Difficulty fetching oci-image creates transient blocked status 

### ISSUE THREAD

**Issue by WRFitch** [canonical/envoy-operator#7]
When running the build_and_deploy integration tests in [this PR](https://github.com/canonical/envoy-operator/pull/5), if raise_on_blocked is set to True when waiting for idle, the test fails. This is due to a transient blocked status, which shows up in the next test in the file, which hangs on "getting oci-image" for around 5 minutes. Since [a blocked status means "I require human intervention"](https://juju.is/docs/olm/status-values), this might just need updating to a maintenance/waiting status. 

Test Logs: 
- without raise_on_blocked: 
  - https://pastebin.canonical.com/p/KhYfYNpy5X/
- with raise_on_blocked: 
  - https://pastebin.canonical.com/p/4Q8jGFg6t4/

**Comment by DomFleischmann** [comment]
The main issue seems that in the integration tests we are not including the `oci-image` resource during deployment, causing the blocked stater, what I don't understand is how it ever gets to active in this state.
